server.port=8080

spring.application.name=roadrescue-api

spring.datasource.url=jdbc:mysql://localhost:3306/roadrescue?createDatabaseIfNotExist=true&useSSL=false

spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

roadrescue.jwt.secret=ThisIsASuperSecureSecretKeyForRoadRescueJWT123456

roadrescue.jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG